[package]
name = "ecm-reader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
libmpegts = "0.3.3"
reqwest = { version = "0.13.3", default-features = false }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
newcamd_lib = { path = "../newcamd_lib" }
